# Generated by Django 3.1.4 on 2021-01-24 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=50)),
                ('book_type', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('img', models.URLField(max_length=5000)),
                ('status', models.CharField(choices=[('Please Choose Status', 'Please Choose Status'), ("I haven't started yet", "I haven't started yet"), ("I'm reading", "I'm reading"), ('I finished', 'I finished')], default='Please Choose Status', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
