# Generated by Django 3.1.4 on 2021-01-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_auto_20210125_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='my_file',
            field=models.FileField(upload_to='upload'),
        ),
    ]
