# Generated by Django 3.1.4 on 2021-01-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0008_auto_20210125_2257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Upload_File',
            new_name='upload_file',
        ),
    ]
